version: '3.8'

services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - .:/workspace/:cached
    command: sleep infinity
  
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - .:/workspace/:cached
    command: sleep infinity
  

    # Add "forwardPorts": ["db:1433"] to **devcontainer.json** to forward MSSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
